{% set name = "netgraph" %}
{% set version = "4.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/netgraph-{{ version }}.tar.gz
  sha256: 982f3d94c43495b57ed3516d41ff00c211a008aa0eebda95ce0b0deec970ad64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base >=1.5
    - rectangle-packer
    - grandalf

test:
  imports:
    - netgraph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/paulbrodersen/netgraph
  summary: Python drawing utilities for publication quality plots of networks.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paulbrodersen
